server:
  port: 8086

spring:
  application:
    name: chatbot-service
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
      embedding:
        model: nomic-embed-text

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
